### ISSUE TITLE
ETH Addresses checksum error

### ISSUE THREAD

**Issue by thecoderpanda** [PowerLoom/snapshotter-lite-multi-setup#1]
When user enters invalid checksum Address for NFT Holder address, the system throws error: 

`web3.exceptions.InvalidAddress: ('web3.py only accepts checksum addresses. The software that gave you this non-checksum address should be considered unsafe, please file it as a bug on their platform. Try using an ENS name instead. Or, if you must accept lower safety, use Web3.toChecksumAddress(lower_case_address).', '0xf41084c75a910abf87a5c669f4b548612a12f720')
`

**Comment by anomit** [comment]
Fixed in PR #2
