### ISSUE TITLE
Proto V2: Prevent local collector creation by passing args

### ISSUE THREAD

**Issue by Seth-Schmidt** [PowerLoom/snapshotter-lite-multi-setup#12]
## Describe the bug 
The local collector component of `snapshotter-lite-v2` is currently only created when an argument is passed to the `build.sh` command. A change for this has been proposed in this PR: https://github.com/PowerLoom/snapshotter-lite-v2/pull/41
An update to the multi-node script behavior is necessary due to the changes introduced in the lite node update.

## To Reproduce
**Affected versions**: e2d771c650bb0e949a93c233f84908e6393adf36

N/A

**Expected behavior**
The multi-node script should pass an argument to `./build.sh` when creation of the local collector needs to be prevented.

**Proposed Solution**
The multi-node script should pass `no_collector` to `./build.sh` when the `new_collector_instance` is False.

**Caveats**
N/A

**Additional context**
This issue was created as a dependency to changes proposed in: https://github.com/PowerLoom/snapshotter-lite-v2/pull/41

**Comment by anomit** [comment]
This was addressed in commit 3e380c0
