### ISSUE TITLE
Support Snapshotter Lite Node V2

### ISSUE THREAD

**Issue by anomit** [PowerLoom/snapshotter-lite-multi-setup#9]
**Is your feature request related to a problem?**
The current setup spins up multiple nodes for the legacy V1 testnet. The [lite node V2](https://github.com/PowerLoom/snapshotter-lite-v2) is not supported yet.

**Describe the solution you'd like**
Pull setup from lite node V2 repository and spawn multiple nodes according to the configured slot IDs.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by anomit** [comment]
This has been implemented in the following branch 

https://github.com/PowerLoom/snapshotter-lite-multi-setup/tree/feat/snapshotter-lite-v2

It supports both `build-dev.sh` and `build.sh` setups of `snapshotter-lite-v2`.  README instructions have been updated.

**Comment by Seth-Schmidt** [comment]
I've ran the setup from scratch while following the instructions exactly as written. The setup was successful, and the node sent its submissions. I did have to login to ghrc, but everything is working fine for me besides access to the image.
